"""Pure data for the small set of UI presets offered by Transcript Quiz."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping


@dataclass(frozen=True)
class VisualPreset:
    """The palette used when the application starts with a preset selected."""

    name: str
    description: str
    appearance_mode: str
    colors: Mapping[str, str]


ELECTRIC_BLUE_COLORS: dict[str, str] = {
    "window": "#080A0D",
    "panel": "#11151A",
    "panel_alt": "#191E25",
    "panel_hover": "#252D36",
    "border": "#2A333D",
    "border_strong": "#3D4956",
    "text": "#F4F6F8",
    "muted": "#9AA5B0",
    "subtle": "#6F7B87",
    "accent": "#2D6BFF",
    "accent_hover": "#3D73E8",
    "accent_soft": "#142A52",
    "on_accent": "#FFFFFF",
    "focus": "#9AB7FF",
    "teal": "#40C995",
    "green": "#40C995",
    "green_dark": "#12392C",
    "success_surface": "#12392C",
    "success_surface_hover": "#194936",
    "success_text": "#B6F0D1",
    "success_border": "#40C995",
    "red": "#F0717B",
    "red_dark": "#42232B",
    "danger_text": "#FFD9DE",
    "amber": "#D8AB55",
    "amber_dark": "#3D3018",
    "warning_text": "#F3D58E",
    "disabled_text": "#74808C",
}


CHERRY_BLOSSOM_COLORS: dict[str, str] = {
    "window": "#FFF9F7",
    "panel": "#FFFFFF",
    "panel_alt": "#FFF0F3",
    "panel_hover": "#F9DCE4",
    "border": "#E8C6CF",
    "border_strong": "#D3AAB7",
    "text": "#3E3940",
    "muted": "#7E7479",
    "subtle": "#A8959C",
    "accent": "#D86D8B",
    "accent_hover": "#C95778",
    "accent_soft": "#F8DDE6",
    "on_accent": "#FFFFFF",
    "focus": "#B96682",
    "teal": "#78B695",
    "green": "#78B695",
    "green_dark": "#DCEFE2",
    "success_surface": "#DCEFE2",
    "success_surface_hover": "#C9E6D3",
    "success_text": "#3E7654",
    "success_border": "#78B695",
    "red": "#C95E70",
    "red_dark": "#F8E0E4",
    "danger_text": "#984858",
    "amber": "#B58A4D",
    "amber_dark": "#F7EBD2",
    "warning_text": "#806332",
    "disabled_text": "#AAA0A4",
}


TIDAL_TEAL_COLORS: dict[str, str] = {
    "window": "#07181C",
    "panel": "#0C252B",
    "panel_alt": "#12353B",
    "panel_hover": "#1B4750",
    "border": "#26515A",
    "border_strong": "#3A6C74",
    "text": "#E7FBFA",
    "muted": "#8BB7B8",
    "subtle": "#5D888C",
    "accent": "#20C7C2",
    "accent_hover": "#3AD8D0",
    "accent_soft": "#123E43",
    "on_accent": "#041214",
    "focus": "#8CF2EA",
    "teal": "#61DED0",
    "green": "#61DED0",
    "green_dark": "#143D36",
    "success_surface": "#143D36",
    "success_surface_hover": "#1C5147",
    "success_text": "#B8F3DC",
    "success_border": "#61DED0",
    "red": "#F47C87",
    "red_dark": "#4B252D",
    "danger_text": "#FFDDE1",
    "amber": "#E0B866",
    "amber_dark": "#4B3A1D",
    "warning_text": "#F7DFA1",
    "disabled_text": "#6D8B8F",
}


AURORA_VIOLET_COLORS: dict[str, str] = {
    "window": "#100C1B",
    "panel": "#1A1428",
    "panel_alt": "#251C38",
    "panel_hover": "#34274D",
    "border": "#43355C",
    "border_strong": "#5B4A78",
    "text": "#F5F0FF",
    "muted": "#B3A8C7",
    "subtle": "#817594",
    "accent": "#9C7BFF",
    "accent_hover": "#B092FF",
    "accent_soft": "#30245A",
    "on_accent": "#130C22",
    "focus": "#D0C0FF",
    "teal": "#63D6C5",
    "green": "#63D6C5",
    "green_dark": "#183E39",
    "success_surface": "#183E39",
    "success_surface_hover": "#24564E",
    "success_text": "#B9F1DF",
    "success_border": "#63D6C5",
    "red": "#F48AAB",
    "red_dark": "#512238",
    "danger_text": "#FFDDE8",
    "amber": "#E7B968",
    "amber_dark": "#4B391D",
    "warning_text": "#F8DFA1",
    "disabled_text": "#7D7190",
}


MOSS_TERMINAL_COLORS: dict[str, str] = {
    "window": "#0B120E",
    "panel": "#111C15",
    "panel_alt": "#19281D",
    "panel_hover": "#263A29",
    "border": "#304735",
    "border_strong": "#46654B",
    "text": "#EAF4E5",
    "muted": "#9AB09A",
    "subtle": "#6F866F",
    "accent": "#91D36B",
    "accent_hover": "#A9E184",
    "accent_soft": "#264326",
    "on_accent": "#0B150D",
    "focus": "#D0F4B2",
    "teal": "#77D0AF",
    "green": "#91D36B",
    "green_dark": "#1E4227",
    "success_surface": "#1E4227",
    "success_surface_hover": "#2B5834",
    "success_text": "#C9F0B0",
    "success_border": "#91D36B",
    "red": "#F18A79",
    "red_dark": "#4D2924",
    "danger_text": "#FFDCD5",
    "amber": "#E4BB63",
    "amber_dark": "#493B1D",
    "warning_text": "#F5DFA1",
    "disabled_text": "#708271",
}


EMBER_STUDY_COLORS: dict[str, str] = {
    "window": "#FFF8F0",
    "panel": "#FFFCF8",
    "panel_alt": "#F6EADF",
    "panel_hover": "#EED8C8",
    "border": "#E1C5B3",
    "border_strong": "#C9A38C",
    "text": "#35251F",
    "muted": "#80685C",
    "subtle": "#AA8D7D",
    "accent": "#C55F32",
    "accent_hover": "#AC4D27",
    "accent_soft": "#F4D8C7",
    "on_accent": "#FFFFFF",
    "focus": "#9E4527",
    "teal": "#5E9F8F",
    "green": "#5E9F8F",
    "green_dark": "#D8E9DF",
    "success_surface": "#D8E9DF",
    "success_surface_hover": "#C3DDCE",
    "success_text": "#356A58",
    "success_border": "#5E9F8F",
    "red": "#C65455",
    "red_dark": "#F5DADB",
    "danger_text": "#8B3638",
    "amber": "#B47B2E",
    "amber_dark": "#F5E8C9",
    "warning_text": "#75541C",
    "disabled_text": "#B5A198",
}


OXBLOOD_LEDGER_COLORS: dict[str, str] = {
    "window": "#170D0E",
    "panel": "#251415",
    "panel_alt": "#351C1F",
    "panel_hover": "#4A272B",
    "border": "#5A3438",
    "border_strong": "#75464A",
    "text": "#F8ECE8",
    "muted": "#BEA4A0",
    "subtle": "#8E706D",
    "accent": "#B94D58",
    "accent_hover": "#D0656F",
    "accent_soft": "#57262E",
    "on_accent": "#FFFFFF",
    "focus": "#F0A0A5",
    "teal": "#76B89D",
    "green": "#76B89D",
    "green_dark": "#1B4033",
    "success_surface": "#1B4033",
    "success_surface_hover": "#285744",
    "success_text": "#BCEBD4",
    "success_border": "#76B89D",
    "red": "#E27A78",
    "red_dark": "#54262A",
    "danger_text": "#FFD9D7",
    "amber": "#D6A45B",
    "amber_dark": "#48351B",
    "warning_text": "#F3D79B",
    "disabled_text": "#876F6D",
}


PARCHMENT_INK_COLORS: dict[str, str] = {
    "window": "#F3EBDD",
    "panel": "#FFF9EF",
    "panel_alt": "#E9DDC8",
    "panel_hover": "#DCC9AC",
    "border": "#CDBB9F",
    "border_strong": "#AA9475",
    "text": "#28231F",
    "muted": "#706354",
    "subtle": "#9D8C76",
    "accent": "#284B63",
    "accent_hover": "#1D394C",
    "accent_soft": "#D6E2E8",
    "on_accent": "#FFFFFF",
    "focus": "#52758A",
    "teal": "#4D8A7A",
    "green": "#4D8A7A",
    "green_dark": "#D8E9DF",
    "success_surface": "#D8E9DF",
    "success_surface_hover": "#C2DDCF",
    "success_text": "#356B57",
    "success_border": "#4D8A7A",
    "red": "#B9504D",
    "red_dark": "#F1D9D4",
    "danger_text": "#853B39",
    "amber": "#A87528",
    "amber_dark": "#F0E2C0",
    "warning_text": "#6D501D",
    "disabled_text": "#A99B89",
}


ARCTIC_GLASS_COLORS: dict[str, str] = {
    "window": "#EDF5F8",
    "panel": "#F9FCFD",
    "panel_alt": "#DDEBF0",
    "panel_hover": "#C9DDE5",
    "border": "#B7CCD5",
    "border_strong": "#91AAB6",
    "text": "#20333B",
    "muted": "#5E7680",
    "subtle": "#8199A2",
    "accent": "#2C7F9D",
    "accent_hover": "#226A84",
    "accent_soft": "#D3E8EF",
    "on_accent": "#FFFFFF",
    "focus": "#4D9FB8",
    "teal": "#4C9C9B",
    "green": "#4C9C9B",
    "green_dark": "#D6EAE2",
    "success_surface": "#D6EAE2",
    "success_surface_hover": "#C1DED3",
    "success_text": "#356B58",
    "success_border": "#4C9C9B",
    "red": "#C75F68",
    "red_dark": "#F4DCDD",
    "danger_text": "#8E3E45",
    "amber": "#AD7C2F",
    "amber_dark": "#F4E7C7",
    "warning_text": "#71531E",
    "disabled_text": "#A2B1B5",
}


MIDNIGHT_ORCHID_COLORS: dict[str, str] = {
    "window": "#0F0C18",
    "panel": "#1B1427",
    "panel_alt": "#281B37",
    "panel_hover": "#3A2850",
    "border": "#4D3863",
    "border_strong": "#6C4F82",
    "text": "#F8F0FF",
    "muted": "#B6A7C4",
    "subtle": "#887794",
    "accent": "#C46DFF",
    "accent_hover": "#D58BFF",
    "accent_soft": "#43245C",
    "on_accent": "#1A0E24",
    "focus": "#E7B8FF",
    "teal": "#6BD1C4",
    "green": "#6BD1C4",
    "green_dark": "#193D39",
    "success_surface": "#193D39",
    "success_surface_hover": "#25554C",
    "success_text": "#BCEFE1",
    "success_border": "#6BD1C4",
    "red": "#F08AAE",
    "red_dark": "#502238",
    "danger_text": "#FFDDE8",
    "amber": "#E5B762",
    "amber_dark": "#49381C",
    "warning_text": "#F5DFA0",
    "disabled_text": "#7F718D",
}


COPPER_CIRCUIT_COLORS: dict[str, str] = {
    "window": "#120F0C",
    "panel": "#211A14",
    "panel_alt": "#302419",
    "panel_hover": "#443522",
    "border": "#5D4930",
    "border_strong": "#806447",
    "text": "#FFF1DA",
    "muted": "#BDA98A",
    "subtle": "#8E7B63",
    "accent": "#D88335",
    "accent_hover": "#EA9B4D",
    "accent_soft": "#583315",
    "on_accent": "#221106",
    "focus": "#F4BB76",
    "teal": "#6BC2AA",
    "green": "#6BC2AA",
    "green_dark": "#174036",
    "success_surface": "#174036",
    "success_surface_hover": "#24584A",
    "success_text": "#BCEEDC",
    "success_border": "#6BC2AA",
    "red": "#E47A70",
    "red_dark": "#552622",
    "danger_text": "#FFDAD5",
    "amber": "#DFB65A",
    "amber_dark": "#49391A",
    "warning_text": "#F4DEA0",
    "disabled_text": "#867562",
}


SAGE_PAPER_COLORS: dict[str, str] = {
    "window": "#EEF2E8",
    "panel": "#FCFDF8",
    "panel_alt": "#E2E9D9",
    "panel_hover": "#D1DDC6",
    "border": "#BBCAB0",
    "border_strong": "#98A98E",
    "text": "#28372D",
    "muted": "#66766A",
    "subtle": "#8D9C8D",
    "accent": "#648B5E",
    "accent_hover": "#53764E",
    "accent_soft": "#D8E6D2",
    "on_accent": "#FFFFFF",
    "focus": "#86A67F",
    "teal": "#5C9B87",
    "green": "#5C9B87",
    "green_dark": "#D5E7D8",
    "success_surface": "#D5E7D8",
    "success_surface_hover": "#C1DDC7",
    "success_text": "#356A4A",
    "success_border": "#5C9B87",
    "red": "#B85B59",
    "red_dark": "#F2DAD5",
    "danger_text": "#843D3B",
    "amber": "#A8782F",
    "amber_dark": "#F0E3C3",
    "warning_text": "#6E521D",
    "disabled_text": "#A3ADA2",
}


DEFAULT_THEME_NAME = "Electric Blue"

THEME_NAMES: tuple[str, ...] = (
    DEFAULT_THEME_NAME,
    "Cherry Blossom",
    "Tidal Teal",
    "Aurora Violet",
    "Moss Terminal",
    "Ember Study",
    "Oxblood Ledger",
    "Parchment & Ink",
    "Arctic Glass",
    "Midnight Orchid",
    "Copper Circuit",
    "Sage Paper",
)

THEME_PRESETS: dict[str, VisualPreset] = {
    DEFAULT_THEME_NAME: VisualPreset(
        name=DEFAULT_THEME_NAME,
        description="A focused dark workspace with electric-blue accents.",
        appearance_mode="dark",
        colors=ELECTRIC_BLUE_COLORS,
    ),
    "Cherry Blossom": VisualPreset(
        name="Cherry Blossom",
        description="A light garden palette with blossom pink and leaf green.",
        appearance_mode="light",
        colors=CHERRY_BLOSSOM_COLORS,
    ),
    "Tidal Teal": VisualPreset(
        name="Tidal Teal",
        description="Deep ocean surfaces with clear, bright teal controls.",
        appearance_mode="dark",
        colors=TIDAL_TEAL_COLORS,
    ),
    "Aurora Violet": VisualPreset(
        name="Aurora Violet",
        description="A night-sky violet palette with a soft aurora accent.",
        appearance_mode="dark",
        colors=AURORA_VIOLET_COLORS,
    ),
    "Moss Terminal": VisualPreset(
        name="Moss Terminal",
        description="A quiet forest-terminal palette built for long study sessions.",
        appearance_mode="dark",
        colors=MOSS_TERMINAL_COLORS,
    ),
    "Ember Study": VisualPreset(
        name="Ember Study",
        description="Warm paper, terracotta controls, and a calm reading surface.",
        appearance_mode="light",
        colors=EMBER_STUDY_COLORS,
    ),
    "Oxblood Ledger": VisualPreset(
        name="Oxblood Ledger",
        description="A dark archival palette with oxblood and parchment-like text.",
        appearance_mode="dark",
        colors=OXBLOOD_LEDGER_COLORS,
    ),
    "Parchment & Ink": VisualPreset(
        name="Parchment & Ink",
        description="A measured paper-and-ink palette for a traditional study desk.",
        appearance_mode="light",
        colors=PARCHMENT_INK_COLORS,
    ),
    "Arctic Glass": VisualPreset(
        name="Arctic Glass",
        description="A crisp blue-white workspace with cool glassy contrast.",
        appearance_mode="light",
        colors=ARCTIC_GLASS_COLORS,
    ),
    "Midnight Orchid": VisualPreset(
        name="Midnight Orchid",
        description="A deep violet night palette with a luminous orchid accent.",
        appearance_mode="dark",
        colors=MIDNIGHT_ORCHID_COLORS,
    ),
    "Copper Circuit": VisualPreset(
        name="Copper Circuit",
        description="A warm technical palette of copper, brass, and green signal tones.",
        appearance_mode="dark",
        colors=COPPER_CIRCUIT_COLORS,
    ),
    "Sage Paper": VisualPreset(
        name="Sage Paper",
        description="A soft botanical paper palette for calm, focused reading.",
        appearance_mode="light",
        colors=SAGE_PAPER_COLORS,
    ),
}


def resolve_theme_name(requested_name: object, fallback: str = DEFAULT_THEME_NAME) -> str:
    """Return a supported preset name without mutating application state."""

    if isinstance(requested_name, str) and requested_name in THEME_PRESETS:
        return requested_name
    if isinstance(fallback, str) and fallback in THEME_PRESETS:
        return fallback
    return DEFAULT_THEME_NAME


__all__ = [
    "ARCTIC_GLASS_COLORS",
    "AURORA_VIOLET_COLORS",
    "CHERRY_BLOSSOM_COLORS",
    "COPPER_CIRCUIT_COLORS",
    "DEFAULT_THEME_NAME",
    "ELECTRIC_BLUE_COLORS",
    "EMBER_STUDY_COLORS",
    "MOSS_TERMINAL_COLORS",
    "MIDNIGHT_ORCHID_COLORS",
    "OXBLOOD_LEDGER_COLORS",
    "PARCHMENT_INK_COLORS",
    "THEME_NAMES",
    "THEME_PRESETS",
    "TIDAL_TEAL_COLORS",
    "SAGE_PAPER_COLORS",
    "VisualPreset",
    "resolve_theme_name",
]
